# Generated by Django 3.0.8 on 2021-05-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queues',
            name='connectedTo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.Business'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.Profile'),
        ),
        migrations.AlterField(
            model_name='business',
            name='queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landing.Queues'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biz', to='Landing.Business'),
        ),
        migrations.AlterField(
            model_name='capacitydata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Profile'),
        ),
        migrations.AlterField(
            model_name='capacitydata',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Business'),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Profile'),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Business'),
        ),
        migrations.AlterField(
            model_name='waittimes',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Landing.Business'),
        ),
    ]
