# Generated by Django 3.0.8 on 2021-04-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitdata',
            name='author',
        ),
    ]
