# Generated by Django 3.1.6 on 2021-06-01 21:52

import Landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='cached_time',
        ),
        migrations.AddField(
            model_name='business',
            name='expiration_time',
            field=models.DateTimeField(default=Landing.models.get_biz_expiration),
        ),
    ]
