# Generated by Django 3.1.6 on 2021-05-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitdata',
            name='business',
        ),
        migrations.RemoveField(
            model_name='waittimes',
            name='reviews',
        ),
        migrations.AddField(
            model_name='waitdata',
            name='waitTimes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Landing.waittimes'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='all_capacity_updates',
        ),
        migrations.AddField(
            model_name='profile',
            name='all_capacity_updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cap_up', to='Landing.capacitydata'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='all_time_updates',
        ),
        migrations.AddField(
            model_name='profile',
            name='all_time_updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_time_up', to='Landing.waitdata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='author',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
