# Generated by Django 3.1.6 on 2021-06-27 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_auto_20210601_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitdata',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
