# Generated by Django 3.1.6 on 2021-05-25 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_auto_20210524_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='all_time_updates',
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_updates', to='Landing.profile'),
        ),
        migrations.AlterField(
            model_name='waittimes',
            name='average',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
