# Generated by Django 3.0.8 on 2021-05-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_auto_20210511_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='queue',
        ),
        migrations.DeleteModel(
            name='Queues',
        ),
        migrations.AddField(
            model_name='skips',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Landing.Business'),
        ),
    ]
