# Generated by Django 3.0.8 on 2021-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_remove_waitdata_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitdata',
            name='author',
            field=models.CharField(default='anonymous', max_length=20),
        ),
    ]
