# Generated by Django 3.1.6 on 2021-03-12 08:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.BinaryField(blank=True),
        ),
    ]
