# Generated by Django 3.1.6 on 2021-05-25 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0003_auto_20210525_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitdata',
            name='numofpeople',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waittimes',
            name='averagePeople',
            field=models.FloatField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='wait_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
