# Generated by Django 3.0.8 on 2021-03-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0004_auto_20210311_0049'),
        ('Landing', '0004_auto_20210312_0806'),
    ]

    operations = [
    ]
