# Generated by Django 3.1.6 on 2021-03-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0004_auto_20210312_0806'),
        ('Landing', '0004_auto_20210311_0049'),
    ]

    operations = [
    ]
