# Generated by Django 3.1.6 on 2021-03-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0005_merge_20210316_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
