# Generated by Django 3.0.8 on 2021-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0005_merge_20210316_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
