# Generated by Django 3.0.8 on 2021-03-30 02:32

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0006_auto_20210323_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.AddField(
            model_name='profile',
            name='search_history',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_history',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='average',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='capacitydata',
            name='capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Landing/pfps'),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='wait_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='waittimes',
            name='average',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
