# Generated by Django 3.0.8 on 2021-04-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0007_auto_20210330_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('xcor', models.FloatField()),
                ('ycor', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='update_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_capacity_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landing.capacityData'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_time_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landing.waitData'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='business',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='waittimes',
            name='business',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='Temp_Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('xcor', models.FloatField()),
                ('ycor', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('cached_time', models.DateTimeField(auto_now=True)),
                ('capacity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.Capacity')),
                ('wait_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.waitTimes')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Landing.Business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesses', models.ManyToManyField(blank=True, null=True, to='Landing.Business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='capacity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap', to='Landing.Capacity'),
        ),
        migrations.AddField(
            model_name='business',
            name='wait_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='Landing.waitTimes'),
        ),
    ]
