# Generated by Django 3.0.8 on 2021-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0008_auto_20210409_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_profile',
            name='businesses',
            field=models.ManyToManyField(blank=True, to='Landing.Business'),
        ),
    ]
