# Generated by Django 3.0.8 on 2021-04-09 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0010_auto_20210409_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitydata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temp_business',
            name='cached_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waitdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 22, 14, 32, 790992)),
        ),
    ]
