# Generated by Django 3.0.8 on 2021-04-09 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0011_auto_20210409_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 22, 25, 17, 727061)),
        ),
    ]
