# Generated by Django 3.0.8 on 2021-04-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0012_auto_20210409_2225'),
        ('Landing', '0006_remove_profile_profile_pic'),
    ]

    operations = [
    ]
