# Generated by Django 3.1.6 on 2021-04-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0006_remove_profile_profile_pic'),
        ('Landing', '0012_auto_20210409_2225'),
    ]

    operations = [
    ]
