# Generated by Django 3.1.6 on 2021-04-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0014_auto_20210415_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='placeID',
            field=models.TextField(default=False, unique=True),
        ),
        migrations.AddField(
            model_name='temp_business',
            name='placeID',
            field=models.TextField(default=False, unique=True),
        ),
    ]
