# Generated by Django 3.1.6 on 2021-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0015_auto_20210420_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_business',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
