# Generated by Django 3.0.8 on 2021-05-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0017_remove_temp_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_business',
            old_name='xcor',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='temp_business',
            old_name='ycor',
            new_name='lon',
        ),
    ]
