# Generated by Django 3.0.8 on 2021-05-01 17:51

import Landing.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0018_auto_20210501_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_history',
            field=Landing.models.ListField(blank=True, null=True, token=','),
        ),
    ]
