# Generated by Django 3.1.6 on 2021-05-07 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0018_auto_20210426_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waittimes',
            name='business',
        ),
        migrations.RemoveField(
            model_name='waittimes',
            name='numReviews',
        ),
        migrations.AlterField(
            model_name='business',
            name='wait_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biz', to='Landing.waittimes'),
        ),
        migrations.CreateModel(
            name='WaitTimeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeToOrder', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('timeTillFood', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waittimes',
            name='reviews',
            field=models.ManyToManyField(related_name='bizWait', to='Landing.WaitTimeReview', verbose_name='list of revews'),
        ),
    ]
