# Generated by Django 3.0.8 on 2021-05-01 20:38

import Landing.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0019_auto_20210501_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_queue', Landing.models.ListField(blank=True, null=True, token=',')),
                ('skip_queue', Landing.models.ListField(blank=True, null=True, token=',')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skips', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('skip_history', Landing.models.ListField(blank=True, null=True, token=',')),
                ('last_pay_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_businesses',
            field=Landing.models.ListField(blank=True, null=True, token=','),
        ),
        migrations.AddField(
            model_name='business',
            name='queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.Queues'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landing.Subscriber'),
        ),
    ]
