# Generated by Django 3.1.6 on 2021-05-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0019_auto_20210507_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='waittimes',
            name='parentTemp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temp_business',
            name='wait_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempbiz', to='Landing.waittimes'),
        ),
    ]
