# Generated by Django 3.0.8 on 2021-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0020_auto_20210501_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_capacity_updates',
            field=models.ManyToManyField(blank=True, related_name='all_cap_up', to='Landing.capacityData'),
        ),
        migrations.AddField(
            model_name='profile',
            name='all_time_updates',
            field=models.ManyToManyField(blank=True, related_name='all_time_up', to='Landing.waitData'),
        ),
    ]
