# Generated by Django 3.0.8 on 2021-05-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0021_auto_20210501_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_business',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temp_business',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
